[2025-03-27T19:54:20.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T19:54:20.350+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_snowflake.elt_process scheduled__2025-03-26T02:45:00+00:00 [queued]>
[2025-03-27T19:54:20.361+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_snowflake.elt_process scheduled__2025-03-26T02:45:00+00:00 [queued]>
[2025-03-27T19:54:20.362+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-27T19:54:20.379+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): elt_process> on 2025-03-26 02:45:00+00:00
[2025-03-27T19:54:20.387+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=614) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T19:54:20.388+0000] {standard_task_runner.py:72} INFO - Started process 647 to run task
[2025-03-27T19:54:20.387+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt_snowflake', 'elt_process', 'scheduled__2025-03-26T02:45:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/join_dag_hw_6.py', '--cfg-path', '/tmp/tmpr1q8f6v_']
[2025-03-27T19:54:20.389+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask elt_process
[2025-03-27T19:54:20.434+0000] {task_command.py:467} INFO - Running <TaskInstance: elt_snowflake.elt_process scheduled__2025-03-26T02:45:00+00:00 [running]> on host edfa4618dc0c
[2025-03-27T19:54:20.510+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_snowflake' AIRFLOW_CTX_TASK_ID='elt_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T02:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-26T02:45:00+00:00'
[2025-03-27T19:54:20.518+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T19:54:20.533+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn1'
[2025-03-27T19:54:20.534+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-27T19:54:20.535+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-27T19:54:20.539+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-27T19:54:20.881+0000] {join_dag_hw_6.py:26} INFO - 
            CREATE OR REPLACE TABLE analytics.temp_session_summary AS 
            SELECT u.*, s.ts
            FROM raw.user_session_channel u
            JOIN raw.session_timestamp s 
            ON u.sessionId = s.sessionId;
        
[2025-03-27T19:54:21.189+0000] {join_dag_hw_6.py:53} ERROR - ELT Process failed: 002003 (42S02): 01bb4b6a-0104-d045-0004-59ff00115e26: SQL compilation error:
Object 'USER_DB_GOPHER.RAW.USER_SESSION_CHANNEL' does not exist or not authorized.
[2025-03-27T19:54:21.198+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/join_dag_hw_6.py", line 27, in elt_process
    cur.execute(sql_ctas)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01bb4b6a-0104-d045-0004-59ff00115e26: SQL compilation error:
Object 'USER_DB_GOPHER.RAW.USER_SESSION_CHANNEL' does not exist or not authorized.
[2025-03-27T19:54:21.215+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt_snowflake, task_id=elt_process, run_id=scheduled__2025-03-26T02:45:00+00:00, execution_date=20250326T024500, start_date=20250327T195420, end_date=20250327T195421
[2025-03-27T19:54:21.242+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T19:54:21.243+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 77 for task elt_process (002003 (42S02): 01bb4b6a-0104-d045-0004-59ff00115e26: SQL compilation error:
Object 'USER_DB_GOPHER.RAW.USER_SESSION_CHANNEL' does not exist or not authorized.; 647)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/join_dag_hw_6.py", line 27, in elt_process
    cur.execute(sql_ctas)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1087, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01bb4b6a-0104-d045-0004-59ff00115e26: SQL compilation error:
Object 'USER_DB_GOPHER.RAW.USER_SESSION_CHANNEL' does not exist or not authorized.
[2025-03-27T19:54:21.288+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T19:54:21.304+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T19:54:21.309+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
