[2025-04-17T12:23:33.044+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T12:23:33.058+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medium_to_pinecone.ingest_to_pinecone manual__2025-04-17T12:22:23.814257+00:00 [queued]>
[2025-04-17T12:23:33.066+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medium_to_pinecone.ingest_to_pinecone manual__2025-04-17T12:22:23.814257+00:00 [queued]>
[2025-04-17T12:23:33.067+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-17T12:23:33.078+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ingest_to_pinecone> on 2025-04-17 12:22:23.814257+00:00
[2025-04-17T12:23:33.092+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medium_to_pinecone', 'ingest_to_pinecone', 'manual__2025-04-17T12:22:23.814257+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/medium_to_pinecone_dag.py', '--cfg-path', '/tmp/tmp_xyso_ge']
[2025-04-17T12:23:33.097+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask ingest_to_pinecone
[2025-04-17T12:23:33.098+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3362) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-17T12:23:33.098+0000] {standard_task_runner.py:72} INFO - Started process 3388 to run task
[2025-04-17T12:23:33.139+0000] {task_command.py:467} INFO - Running <TaskInstance: medium_to_pinecone.ingest_to_pinecone manual__2025-04-17T12:22:23.814257+00:00 [running]> on host c4a090d2ac67
[2025-04-17T12:23:33.195+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medium_to_pinecone' AIRFLOW_CTX_TASK_ID='ingest_to_pinecone' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T12:22:23.814257+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T12:22:23.814257+00:00'
[2025-04-17T12:23:33.197+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T12:23:34.607+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/medium_to_pinecone_dag.py", line 57, in upsert_to_pinecone
    index.upsert(vectors=vectors)
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/utils/error_handling.py", line 10, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 171, in upsert
    return self._upsert_batch(vectors, namespace, _check_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 194, in _upsert_batch
    vectors=list(map(vec_builder, vectors)),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 190, in <lambda>
    vec_builder = lambda v: VectorFactory.build(v, check_type=_check_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/vector_factory.py", line 56, in build
    return VectorFactory._tuple_to_vector(item, check_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/vector_factory.py", line 70, in _tuple_to_vector
    return Vector(id=id, values=convert_to_list(values), metadata=metadata or {}, _check_type=check_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 42, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model/vector.py", line 275, in __init__
    self.id = id
    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 181, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 481, in __setitem__
    self.set_attribute(name, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 153, in set_attribute
    value = validate_and_convert_types(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 1550, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
pinecone.core.client.exceptions.PineconeApiTypeError: Invalid type for variable 'id'. Required value type is str and passed type was int at ['id']
[2025-04-17T12:23:34.626+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=medium_to_pinecone, task_id=ingest_to_pinecone, run_id=manual__2025-04-17T12:22:23.814257+00:00, execution_date=20250417T122223, start_date=20250417T122333, end_date=20250417T122334
[2025-04-17T12:23:34.647+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T12:23:34.648+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 111 for task ingest_to_pinecone (Invalid type for variable 'id'. Required value type is str and passed type was int at ['id']; 3388)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/medium_to_pinecone_dag.py", line 57, in upsert_to_pinecone
    index.upsert(vectors=vectors)
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/utils/error_handling.py", line 10, in inner_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 171, in upsert
    return self._upsert_batch(vectors, namespace, _check_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 194, in _upsert_batch
    vectors=list(map(vec_builder, vectors)),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/index.py", line 190, in <lambda>
    vec_builder = lambda v: VectorFactory.build(v, check_type=_check_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/vector_factory.py", line 56, in build
    return VectorFactory._tuple_to_vector(item, check_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/data/vector_factory.py", line 70, in _tuple_to_vector
    return Vector(id=id, values=convert_to_list(values), metadata=metadata or {}, _check_type=check_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 42, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model/vector.py", line 275, in __init__
    self.id = id
    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 181, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 481, in __setitem__
    self.set_attribute(name, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 153, in set_attribute
    value = validate_and_convert_types(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/core/client/model_utils.py", line 1550, in validate_and_convert_types
    raise get_type_error(input_value, path_to_item, valid_classes,
pinecone.core.client.exceptions.PineconeApiTypeError: Invalid type for variable 'id'. Required value type is str and passed type was int at ['id']
[2025-04-17T12:23:34.686+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T12:23:34.706+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T12:23:34.708+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
